### ISSUE TITLE
users/:id 페이지 접근 관련

### ISSUE THREAD

**Issue by zzulu** [ShinJaehun/checkjjaek#20]
사용자가 아무런 책을 등록하지 않았을 경우, 오류가 납니다.
사용자의 책들을 불러와 정보를 보여줄 때 문제가 있는 것 같습니다.

**Comment by zzulu** [comment]
코드를 잠깐 보았는데
'마지막 책짹' 부분의 `<%= @user.posts.last.created_at.to_date %>`에서 오류가 있습니다.
사용자가 책을 등록하지 않았다면 `posts`는 비어있기 때문에, `.last`를 할 경우 `nil`이 나오게 되어 뒷부분 코드들의 실행에서 오류가 발생합니다.

이를 방지하기 위해서는 posts가 비어있는지 아닌지에 대한 검사가 필요합니다.
if를 사용하셔도 좋고, 아래처럼 ruby의 **Safe Navigation Operator**로 해결하셔도 좋습니다.

```ruby
@user.posts.last&.created_at&.to_date || '-'
```

**Comment by ShinJaehun** [comment]
그동안 if 문을 이용해서 이런 식으로 처리했었어요.
Safe Navigation Operator, 이런 게 있었군요! 잘 사용하겠습니다.

```
<% if @user.posts.last %>
          <div style="margin: 5px 0"><strong class="text-muted">마지막 책짹</strong>&nbsp;&nbsp;<%= @user.posts.last.created_at.to_date %></div>
<% end %>

```
